name: unit_test
on:
  pull_request:
    branches : [ "dev","main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install
      run: pip install -r requirements.txt
    - name: Unit tests
      run: python -m unittest tests/test_employee_methods.py
